//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_group { get; set; }
        public Nullable<int> course { get; set; }
        public Nullable<int> zaochnoe { get; set; }
        public Nullable<System.DateTime> dateExit { get; set; }
        public Nullable<System.DateTime> dateIn { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
