//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudent
    {
        public Nullable<System.DateTime> dateIn { get; set; }
        public Nullable<System.DateTime> dateExit { get; set; }
        public Nullable<int> zaochnoe { get; set; }
        public Nullable<int> course { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string LittleName { get; set; }
        public int Id { get; set; }
    }
}
